summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-freebsd-13.2-amd64/releases/download/2023.12.09/pkg-config-0.29.2-freebsd-13.2-amd64.tar.xz
bin-sha: ecc7a8af4621a96dd923de31700dc436a711cdde65c2bfee3a23f1fc627cdf38
