name: publish

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: [bash, base16, base64, bat, bsdtar, bc, bison, bmake, bzip2, b3sum, cmake, coreutils, curl, d2, darkhttpd, diffutils, dos2unix, dot_static, doxygen, ed, file, figlet, flex, flock, findutils, fzf, gawk, getopt, gettext-tools, gh, gindent, git, glib-tools, gm4, gmake, gn, go-md2man, golang, gperf, grep, gsed, gtar, gzip, jq, lolcat, lzip, lz4, nasm, ninja, openssl, orcc, p7zip, patchelf, patch, pkgconf, potrace, re2c, rsync, sassc, scdoc, swig, sqlite3, sysinfo, t1utils, tic, tree, trietool, uctags, unzip, uppm, xmake, xmlutils, xsltproc, xxd, xz, yasm, yq, zip, zstd, zoxide]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - uses: cross-platform-actions/action@master
        with:
          operating_system: freebsd
          version: ${{ matrix.version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install freebsd-13.2-amd64/${{ matrix.pkg }} --static
            run ./ppkg bundle  freebsd-13.2-amd64/${{ matrix.pkg }} .tar.xz

            PACKAGE_SUMMARY="$(./ppkg receipt freebsd-13.2-amd64/${{ matrix.pkg }} summary)"
            PACKAGE_VERSION="$(./ppkg receipt freebsd-13.2-amd64/${{ matrix.pkg }} version)"
            PACKAGE_WEB_URL="$(./ppkg receipt freebsd-13.2-amd64/${{ matrix.pkg }} web-url)"

            PACKAGE_BIN_FILENAME="${{ matrix.pkg }}-$PACKAGE_VERSION-freebsd-13.2-amd64.tar.xz"

            PACKAGE_BIN_SHA="$(sha256sum "$PACKAGE_BIN_FILENAME" | cut -d ' ' -f1)"

            PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-freebsd-13.2-amd64/releases/download/@TAGNAME@/$PACKAGE_BIN_FILENAME"

            cat > ${{ matrix.pkg }}.yml <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION 
            bin-url: $PACKAGE_BIN_URL 
            bin-sha: $PACKAGE_BIN_SHA
            EOF

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ${{ matrix.pkg }}-*-freebsd-13.2-amd64.release.tar.xz
            ${{ matrix.pkg }}.yml


  publish:
    needs: build

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls

      - run: mv *.yml formula/

      - name: create notes.md
        run: |
          cat > notes.md <<EOF
          These packages are created by [ppkg](https://github.com/leleliu008/ppkg).

          These packages are statically linked.

          These packages are relocatable which means that you can install them to anywhere.
          EOF

      - name: publish
        run: |
          TAGNAME="$(date +%Y.%m.%d)"

          sed -i "s|@TAGNAME@|$TAGNAME|" formula/*.yml

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          git config --global user.name  leleliu008
          git config --global user.email leleliu008@gmail.com

          git add formula
          git commit -m "publish new version $TAGNAME"
          git push origin master
